### ISSUE TITLE
Any Release version?

### ISSUE THREAD

**Issue by Incubator85653** [evshiron/SokuMKII-nwjs#1]
I've found this tool, a zip archive in many discuss group, and track it here.
And then, I have not found the official site and any other valid information like where did you publish it.
It just an archive appear in the discuss group without license, source code or something.

I never learned JavaScript before.
There isn't any release could be download on Github, but the archive I found obviously is a binary archive.
How do you build it? And how could we build it from source?

**Comment by evshiron** [comment]
如果我没猜错你应该是国主吧。
屎玉已经很久没有更新（其实是有一些小更新但是没推送的），而且因为使用的语言是TypeScript，代码质量堪忧，我不建议继续在这个项目上改写（其实整个Soku系列都很差劲）。
毛玉和屎玉的原理都很简单：在公网服务器上打开一个临时UDP端口，和客户端绑定，并中转收到的数据。
如果你对这块感兴趣，我推荐你看看STUN协议（新版），TRUN协议和ICE协议，这是能够超越毛玉和屎玉的突破点，也是我没有时间继续做下去的地方。

**Comment by Incubator85653** [comment]
@evshiron highlight other one's identity on GitHub is very rude. Edit your comment and remove that as soon as possible.

I don't understand what are u talking about. No, I'm not ask to become a contributor.
I'm looking for a trusted binary source to prevent malware or virus or spyware for my gamers.

Just simply draft a release, or create a tutorial page for "How to build from source code" to end this talk.

**Comment by evshiron** [comment]
@Incubator85653 Cool. Edited.
```shell
git clone https://github.com/evshiron/SokuMKII-nwjs
cd SokuMKII-nwjs
npm install typescript typings -g
npm install
typings install
npm run dist
# Now things should be in the `./build/` directory. Pack with a nw.js binary (0.13.x is recommended) and you are here to go.
```

**Comment by evshiron** [comment]
The workflow was built several months ago, and I won't guarantee the above steps will work as expected.
And be aware as I no longer play this game, the provided servers might be closed at any time (as you know I have explained why above). If you are to provide services for your gamers, be sure to make your own set of relay servers. The server-side code is provided in [evshiron/SokuMKII-TypeS](https://github.com/evshiron/SokuMKII-TypeS) and [evshiron/SokuMKII-TypeM](https://github.com/evshiron/SokuMKII-TypeM) (although you can definitely write your own one rather easily).
BTW I am not expecting you as a contributor, because these are a bunch of projects I have abandoned for some (long) time. Good luck.
